refactor: IrmaMobileBridgePlugin to Swift
privacybydesign/irmamobile pull request #192
Opened 2023-05-25 08:44 UTC by sjoerdlmkns

2023-05-25 08:54 UTC, sjoerdlmkns commented
After some debugging I believe it gets stuck on this line. So the way things are setup doesn't seem to be right. 

https://github.com/privacybydesign/irmamobile/blob/2642d9e0691247a3f06224e1e062b420770853f5/irmagobridge/receive_event.go#L17

2023-05-30 13:21 UTC, ivard commented
@sjoerdlmkns I think I fixed it. Can you check whether you're happy with the result? Then we can 'undraft' the PR.

2023-05-30 14:06 UTC, sjoerdlemkens commented
Yes it works now. Looks really good! Definitely a step up from what we had before. Thanks!

2023-05-30 14:11 UTC, sanderhollaar approved these changes

2023-05-30 14:11 UTC, ivard approved these changes

2023-05-30 14:19 UTC, ivard requested changes

2023-05-30 14:19 UTC, ivard commented on ios/Runner/IrmaMobileBridgePlugin.swift
> +}
We need to update the CHANGELOG still.

2023-05-31 06:36 UTC, bobhageman approved these changes

2023-05-31 07:40 UTC, sanderhollaar approved these changes

2023-05-31 08:44 UTC, ivard approved these changes

2023-05-31 08:48 UTC, merged