Ux 2.0 HomeTab
privacybydesign/irmamobile pull request #83
Opened 2023-01-23 08:29 UTC by sjoerdlmkns

2023-01-23 16:02 UTC, ivard requested changes

2023-01-24 07:59 UTC, sjoerdlmkns commented on lib/src/screens/session/disclosure/widgets/disclosure_permission_choices_screen.dart
> +              //TODO Fix the styling here again
![Simulator Screen Shot - iPhone 14 - 2023-01-24 at 08 55 18](https://user-images.githubusercontent.com/97674344/214238936-eb8778f8-65ba-4c48-b5cb-8ae613487e3e.png)

In the attribute request flow the action card is used in a different way so i thought tweaking the widget further in that story would be a good idea.

2023-01-24 09:54 UTC, ivard commented on lib/src/screens/session/disclosure/widgets/disclosure_permission_choices_screen.dart
> +              //TODO Fix the styling here again
Ah okay that makes sense :+1:

2023-01-24 09:55 UTC, ivard commented on lib/src/widgets/yivi_themed_button.dart
> +          isTransparent != true || style != YiviButtonStyle.fancy,
Minor nitpick, but `!isTransparent` is shorter :)

2023-01-24 10:27 UTC, ivard approved these changes

2023-01-24 13:50 UTC, bobhageman approved these changes

2023-01-24 13:50 UTC, merged