Ux 3.0 AddDataScreen
privacybydesign/irmamobile pull request #86
Opened 2023-01-26 08:45 UTC by sjoerdlmkns

2023-01-27 10:03 UTC, ivard requested changes

2023-01-27 12:18 UTC, sjoerdlmkns commented on lib/src/screens/activity/widgets/activity_card.dart
> +                  initials: title[0],
You are right ,`''[0]` is unsafe and causes an error. I changed it.

2023-01-27 13:20 UTC, ivard approved these changes

2023-01-30 07:22 UTC, sanderhollaar approved these changes

2023-01-30 07:22 UTC, merged